[package]
name = "totp_cli"
version = "0.1.0"
edition = "2021"

[dependencies]

totp-rs = { version = "3.1.0", features = ["otpauth"] }

clap = { version = "4.0.26", features = ["derive"] }
termcolor = "1.1.3"
atty = "0.2"
